baseURL = 'https://buccalcone.github.io/'
languageCode = 'ja'
canonifyurls = false
publishDir = 'public'
title = '中腸腺'
paginate = 5
theme = 'papermod'
enableEmoji = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
title = '中腸腺'
description = 'Blog of buccalcone'
keywords = [ 'Blog', 'Portfolio', 'PaperMod' ]
author = 'buccalcone'
images = [ 'profile.jpg' ]
DateFormat = 'January 2, 2006'
defaultTheme = 'auto'
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

#  [params.assets]
#  favicon = 'Thinking_Face_Emoji_large.png'
#  favicon16x16 = 'Thinking_Face_Emoji_large.png'
#  favicon32x32 = 'Thinking_Face_Emoji_large.png'
#  apple_touch_icon = 'Thinking_Face_Emoji_large.png'
#  safari_pinned_tab = 'Thinking_Face_Emoji_large.png'

#
# トップページの文字やアイコンの設定
#
  [params.label]
  text = '中腸腺'
  iconHeight = 35

#
# ProfileModeの設定
#
  [params.profileMode]
  enabled = true
  title = 'buccalcone'
  subtitle = 'Interest in Computer Architecture.'
  imageUrl = 'buccalcone.png'
  imageWidth = 150
  imageHeight = 150
  imageTitle = 'my image'

#  subimageUrl = 'buccalcone.png'
#  subimageWidth = 100
#  subimageHeight = 100
#  subimageTitle = 'my image'

# QRCode 貼り付ける用
#  qrImageUrl = 'qr-code.png'
#  qrimageWidth = 150
#  qrimageHeight = 150
#  qrimageTitle = 'qr code'

  [params.profileMode.qrcode]
    enabled = true
#
# SNSアイコンとかリンクの設定
#
  [[params.socialIcons]]
  name = 'x'
#  url = 'https://x.com/buccalcone_'

  [[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/buccalcone'

  [[params.socialIcons]]
  name = 'youtube'
  url = https://www.youtube.com/@bukkalcone

  [[params.socialIcons]]
  name = 'note'
  # url = 'https://buccalcone.github.io/index.xml'

  [[params.socialIcons]]
  name = 'qiita'
  # url = 'https://buccalcone.github.io/index.xml'
  
  [[params.socialIcons]]
  name = 'rss'
  url = 'https://buccalcone.github.io/index.xml'

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = 'https://github.com/buccalcone.github.io/content'
  Text = 'Suggest Changes'
  appendFilePath = true

#
# search/ 検索機能の設定
#
  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  limit= 10
  keys = [ 'title', 'permalink', 'summary', 'content' ]

#
# メニューバーの設定
#

[[menu.main]]
identifier = 'profile'
name = 'Profile'
url = 'profile'
weight = 5

[[menu.main]]
identifier = 'blog'
name = 'Blog'
url = 'blog/'
weight = 10

[[menu.main]]
name = 'Archives'
url = '/archives'
weight = 15

[[menu.main]]
name = 'Search'
url = 'search/'
weight = 20

[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = 'tags/'
weight = 25

[[menu.main]]
identifier = 'slide'
name = 'Slide'
url = 'https://buccalcone.github.io/slides/'
weight = 30
